name: pre-release

on:
  push:
    branches:
      - master

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build app
        run: |
          npm ci
          npm run build
          cp config.example.js build
          pushd build
          zip -qr "../TileBoard.zip" .

      - uses: marvinpinto/action-automatic-releases@v1.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            TileBoard.zip
